### ISSUE TITLE
Resizing window

### ISSUE THREAD

**Issue by iamjaydear** [jfchapman/VUPlayer#1]
I'm using v4.2 on a Dell Vostro 3550 laptop. The width is adjustable within limits which is fine, but the height can only be increased. The problem is that it already exceeds my screen's height and the status bar at the bottom is not visible. If I maximise the window the status bar is visible, but of course the program is then occupying the entire screen. I must say the VU Meters and the Pitch control are great, many thanks. I hope you can fix the variable sizing issue.

**Comment by jfchapman** [comment]
There's a minimum hardcoded app size of 1024 x 768, so you won't be able to reduce the size below that. I'll look into relaxing this.

**Comment by iamjaydear** [comment]
That'd be good... this screen is 1366x768, but of course you lose the height of the taskbar. It's interesting to note that full screen mode does reduce the height to allow for that.

**Comment by norrisgc** [comment]
As a long time VUPlayer user, I'm very pleased to see this new version.

One of the great things about version 2 was that it was very compact. Version 4 isn't, and a large part of the reason for that is this minimum height, so for that reason I'd also like this minimum height limit reduced significantly.

**Comment by iamjaydear** [comment]
I'm now using v2.49. The VU meters are lovely but I'd like to be able to make them smaller like in the separate 'VUmeter' app :)  

V2.49 has much, much better sizing, I can play random mp3's, the gui is great, the EQ frequencies are sensible, the options are very good, and it's quick to open, no complaints here. Glad I found out about v2.49. One suggestion - add mp3 format including vbr (via LAME 3.100, etc.) to converter.

**Comment by jfchapman** [comment]
The minimum window size has been reduced to 640 x 480, as of v4.3.
