### ISSUE TITLE
support folder scan

### ISSUE THREAD

**Issue by pipiscrew** [jfchapman/VUPlayer#10]
hi,

looks strong, but there is no folder support.

- Drag&Drop a folder to window 0%
- On 'build in explorer' when I have a folder contains folders, should be an option (to context menu) to add all files to playlist (or by CTRL+LCLICK, to do a recursive scan)

**Comment by jfchapman** [comment]
There is drag & drop support onto the playlist window (when it's showing a playlist), so it should work. Agreed, it would be nice to have drag & drop support onto the tree view, so I will review this.
An additional context menu option is also a good idea, so I'll add it to the TODO list.

**Comment by jfchapman** [comment]
For version 4.13, I've added an 'add to playlist' option on the tree context menu. This will add the tree item and all sub items to the selected playlist.

**Comment by pipiscrew** [comment]
looks nice man!
