### ISSUE TITLE
Feature: Make it a little more friendly with screen readers

### ISSUE THREAD

**Issue by Cristianleon17** [jfchapman/VUPlayer#11]
Hi, I use VuPlayer since 2011. I am still usin the legacy version because it is awesome.
And now I did a Github account only for open an issue here because I want to use the new version in a confortable way.
I really don't know how to use this platform properly, so I am sorry if I do something bad.

So, I am a screen reader user, and I want to navigate between the lists, TOOLBARS and trees of the program with my screen reader properly, LIKE IN the 2.49 version.
If you could add this feature I definitely will update to this new version, which looks great.
I don't know anything about programming, but if you need my help, count me in.
Thank you so much!

**Comment by jfchapman** [comment]
Thanks for the feedback.
I do need to review the keyboard navigation for the whole application. Not being a big keyboard shortcut user, I have probably overlooked some things that need fixing! 
Definitely, it should be possible to navigate around the application, as with the legacy versions, so hopefully this will be resolved for the next version.

Best regards,
James

**Comment by 2367994109** [comment]
please add VST

**Comment by jfchapman** [comment]
Version 4.10 now contains some fixes for keyboard and screen reader usage. Specifically, tabbing between the list and tree views should now work properly. It is not possible to tab between to toolbar controls, but there are shortcut keys for all of these functions. Thanks for pointing out the problems, as it prompted me to do some testing with Windows Narrator, which highlighted many issues with the application!!
