### ISSUE TITLE
Avast is saying vulpayer is trying to access login info in Firefox

### ISSUE THREAD

**Issue by raphaelmsx** [jfchapman/VUPlayer#12]
Avast is saying vulpayer is trying to access login info in Firefox, please see screenshot below:

[https://imgur.com/jNEzUY2](url)

I also posted on Avast forum...

**Comment by jfchapman** [comment]
I'm not sure what the problem is there, as I am not an Avast or Firefox user.
The only time VUPlayer requires internet access is when using Audioscrobbler functionality, which uses the Audioscrobbler 2.0 API,
