### ISSUE TITLE
Please add stream radio support aac/hls/mp3

### ISSUE THREAD

**Issue by goodbitlabsuz** [jfchapman/VUPlayer#14]
Hi,
Thank's for your player
Will be cool if you add strream radio support aac/hls/mp3

Thank's advance

**Comment by jfchapman** [comment]
Yep, this will be in the next version.

**Comment by jfchapman** [comment]
For version 4.10, I've added support for HLS, MP3 & AAC streams.
The M3U & PLS handling code has been updated to support internet streams, and stream URLs can also be added manually to the playlist.

**Comment by goodbitlabsuz** [comment]
Big thank's bro
Upcoming Happy New Year

Please next release add
user-agent  some radio stations required user agent

Thank's advance

пн, 28 дек. 2020 г. в 22:39, James Chapman <notifications@github.com>:
