### ISSUE TITLE
Please improve streaming add support user-agent for streaming radio and get information audio tag song,author etc

### ISSUE THREAD

**Issue by goodbitlabsuz** [jfchapman/VUPlayer#16]
Big thank's for streaming radio support
Please add support user-agent for streaming radio some station don't work without user-agent
and get information audio tag song,author etc
Thank's advance

**Comment by jfchapman** [comment]
For version 4.12, added support for stream titles (specifically the SHOUTcast style 'StreamTitle' tag), which will be displayed in the application title bar and systray tooltip when available. Also set the user agent string.
