### ISSUE TITLE
Cannot assign play/pause as hotkey

### ISSUE THREAD

**Issue by raphaelmsx** [jfchapman/VUPlayer#18]
Hi.

I'm unable to assign the keyboard play/pause key as any hot key.

In other words: I could assign the F9 key to action play/pause , but ideally I wanted to assign the action play/pause to the dedicated play/pause key on the keyboard.

Thanks!

**Comment by jfchapman** [comment]
Added support for media keys in version 4.12, so they should now work when the application has keyboard focus. They can also be assigned as hot keys.

**Comment by raphaelmsx** [comment]
Hi again.

First, thanks for your attention, but I can't still assign play/pause hotkey for action play/pause in version 4.12

If it's any help, I'm on Win10 and my keyboard is a "Microsoft Wired 600", which has 4 media keys: play/pause, vol-, vol+ and mute. 

I can assign those last three to play/pause action, but not the play/pause key. 

Thanks.

**Comment by sergeevabc** [comment]
Aggrrhh, why combinations with Win (e.g. <kbd>Win+F5</kbd>) key are not supported?
