### ISSUE TITLE
VuPlayer always creating a "Ephemera" playlist

### ISSUE THREAD

**Issue by gekar** [jfchapman/VUPlayer#19]
Hi,

Not sure it's an issue or should be considered as a request.

When VuPlayer is set as default player for some file type, after a double-clic on a song file (.mp3 or whatever) from Windows Explorer, VuPlayer always creates a new playlist, called "Ephemera". Other files of the same location are not displayed so cannot be selected without browsing "Computer view" (to find again same directory, which requests several clics).

By default, why not open the "Computer view" and show all file at same location, instead of forcing a playlist creation ?
Or would it be possible to allow this behaviour as an option ?

**Comment by jfchapman** [comment]
I'll have a think about where to move this default playlist. It's used when launching or calling the app with any files.
The other possibility is 'now playing' playlist to show the current queue, with maybe some 'play next', 'queue song' options, etc.

**Comment by jfchapman** [comment]
For version 4.13, I've just renamed the 'ephemera' playlist to 'Default Playlist', which hopefully is a bit more generic. 
I couldn't find anywhere better to put it, so it will still appear in the playlists node.

**Comment by gekar** [comment]
Hi and thx for the answers.

In my case, 4.13 still creates ephemera list, but it's not really important. My opinion remains that it'd have been more logical to open VuPlayer "Computer" view (expanded to the current directory) when no playlist is active. In that way, other songs could have been selected immediatly from VuPlayer. For now, you have to go out of VuPlayer to select another song, even if it was simply the next one of the same directory (or try to locate yourself the same directory from the collapsed Computer" view...)

Well, maybe it's not possible or everyone is using playlists all the time but me ?...
Great soft anyway.
