### ISSUE TITLE
Removing tracks

### ISSUE THREAD

**Issue by iamjaydear** [jfchapman/VUPlayer#2]
I don't seem to be able to remove tracks. Ctrl+R does not work, the (-) button is greyed out and the Remove Track(s) option in the File menu is greyed out too. Help!

**Comment by jfchapman** [comment]
It's only possible to remove tracks from playlists or favourites. The option will be grayed out for any other type of list (all files, artist, genre, etc.), so this may be what is happening?

**Comment by iamjaydear** [comment]
Ahah, I should have realised. I don't use playlists much so it didn't occur to me.
