### ISSUE TITLE
Re-add triple and quadruple click please

### ISSUE THREAD

**Issue by alid33** [jfchapman/VUPlayer#20]
Hi James,
Thanks for a great player which is both powerful and small!
Just a quick request: in v2.49 and previous there was an option to configure the triple-click and quadruple-click actions when VUPlayer was minimised to the system tray. I found this really useful and miss it in the new version - any chance of reinstating please? I know I can control it with function keys and can map hotkeys but I find being able to click on the system tray without switching to the program really convenient.
Thanks for all your work on this.
Ali

**Comment by jfchapman** [comment]
Sure thing, I'll try and add it back into the next version.

**Comment by jfchapman** [comment]
I've added triple & quadruple click options for the latest release (v4.13).

Thanks,
James

**Comment by alid33** [comment]
Hi James,
Thanks very much for doing that - it is great to be able to control my music so easily from the system tray again.
FYI My favoured settings are 1 click = Play/Pause, 2 = Show/Hide VUPlayer, 3 = Next, 4 = Previous
Best wishes
Ali
