### ISSUE TITLE
New VU Player no longer "stays on top" in Windows 10

### ISSUE THREAD

**Issue by 027Wayne** [jfchapman/VUPlayer#23]
Just curious--I've used VU player (the old 32-bit version)  over the years because it was the only one that could remain on top (in focus) when typing in Microsoft Word on the same screen to transcribe recordings. Now with two screens, it's not such a big issue, but does the capability still exist? If not, can it? I'm running 64-bit Windows 10. BTW: the earlier version played well with Microsoft Word running in WINE on Ubuntu 16 and 18--also remaining on top.

**Comment by jfchapman** [comment]
Hi,

Always on top is one of the things I never got around to copying over from the old version. It's a simple thing to do, so I'll add it to the next version.

Thanks,
James

**Comment by 027Wayne** [comment]
Hi James,

I’m sure not too many people need that sort of thing, but I used to tell people it was the  only player I could find with “always on top” capability—back when we only had  one screen. Those players that didn’t have always on top would lose the control capability once you started typing in Word. So for transcribing, it was perfect!  I would set up F7, F8 and F9 function keys for  back 5 seconds—play-pause—and forward five seconds, which kept them near my normal typing keys. J

 

Thanks for responding!

Wayne

**Comment by jfchapman** [comment]
Hi,
The latest release (v4.14) now has an 'Always on Top' setting in the View menu.

Thanks,
James

**Comment by 027Wayne** [comment]
Thanks so much.

I’ll check it out.

Wayne
