### ISSUE TITLE
Stopping at the end of track doesn't remain

### ISSUE THREAD

**Issue by mapoky** [jfchapman/VUPlayer#25]
When selecting "Stop at Track end" (F2 key), this option is automatically turned off after each track, so I have to turn it on over and over again! BTW, this feature worked fine in version 2.49

**Comment by jfchapman** [comment]
Hi,
Yes this is one of the options that never got ported over to the new version, I will try and add it for the next release.

Thanks,
James

**Comment by jfchapman** [comment]
I've added an option in the latest release (v4.14) to retain the 'Stop at Track End' setting, in the general options page (by default it's not enabled).

Thanks,
James
