### ISSUE TITLE
Mini controls when I hover my mouse to the app at my taskbar

### ISSUE THREAD

**Issue by ScottsplaysSus** [jfchapman/VUPlayer#26]
Hey devs, is it possible to add some controls when I hover my mouse to the app icon at my Windows taskbar? Here are some examples of other apps when I hover my mouse to the app icon at my taskbar: 

<img width="160" alt="2021-12-03 18_02_16-" src="https://user-images.githubusercontent.com/91255736/144584843-e796b9e9-9c04-418c-9b02-c645917cd9c8.png">

<img width="160" alt="image" src="https://user-images.githubusercontent.com/91255736/144584918-6c86223b-1545-484c-ba4a-3970ec9b1a3c.png">

I hope you can add this feature. Thank you for creating and maintaining such a wonderful music player :D

**Comment by jfchapman** [comment]
Yes, this would be a nice feature to have.
I will have a look at the taskbar extensions interface to see how difficult it would be to add.

Thanks,
James

**Comment by ScottsplaysSus** [comment]
Thanks for the reply :D Looking forward for this feature to be added :)

**Comment by jfchapman** [comment]
The latest release (v4.14) now has a toolbar in the taskbar thumbnail preview window:

![image](https://user-images.githubusercontent.com/8337482/170825151-1de8ef77-b49f-4986-ac51-5bc87a468d08.png)

There's also an option (in the taskbar options page) to change the button colour.

This feature is only for Windows 10 and above, as it did not look too great when I tested it on Windows 7 (where I am limited to a virtual machine).

Thanks,
James
