### ISSUE TITLE
Toggle on/off Title on Playlist Columns

### ISSUE THREAD

**Issue by SrBalok** [jfchapman/VUPlayer#28]
In the next version release, please consider allow the user to show/hide the "Title" column like the other columns.  Thank you.

**Comment by jfchapman** [comment]
In the latest release (v4.14) it is now possible to hide the 'Title' column.
I also renamed the 'File Name' column to 'File Path', and added a proper 'File Name' column (which displays just the file name).
Also, to ensure at least one column is always visible, if all columns are hidden then I force the 'File Path' column to be shown.

Thanks,
James
