### ISSUE TITLE
[Feature request] Add support for OpenMPT (.mptm) format

### ISSUE THREAD

**Issue by c0d3h4x0r** [jfchapman/VUPlayer#34]
Long-time user (since before 2010!), first time feature requester!  (I'm known in the tracker scene as [SYRiNX](https://modarchive.org/index.php?request=view_profile&query=94893).)

On my iPhone, I'm acclimated to using **Modizer** (which uses [`libopenmpt`](https://github.com/OpenMPT/openmpt/tree/master/libopenmpt) for listening to playlists of tracker modules (including my own **OpenMPT** [`*.mptm`] compositions) on the go.

It would be amazing if **VUPlayer** could also support `*.mptm` files via `libopenmpt`.

I'm guessing the most difficult part would be building it alongside your own code and possibly wrapping its API inside something that works similar enough to BASS.  I'm a C++ developer, so I'd be happy to take a crack at it myself in my own fork, so long as I know you're open to the idea and to an outside contributor.

**Comment by c0d3h4x0r** [comment]
I've got a good start on this in my own fork.

**Comment by jfchapman** [comment]
Hi! Thanks for trying out the new version of the app.

I've tested the OpenMPT library before, and it looks good, certainly easy to use. 
I've put a branch up here, which uses libopenmpt instead of the BASS decoder for tracker files:
https://github.com/jfchapman/VUPlayer/tree/libopenmpt_test

If this was to go into the main release, I would probably need to add some options & UI to choose between BASS and libopenmpt, as they obviously decode a little differently.

Anyway, I hope that's some use, let me know what you think.

James

**Comment by c0d3h4x0r** [comment]
Oh nice... you've already coded exactly what I was 80% of the way through doing 👍   I've cloned, built, and tried your branch, and it plays back my `*.mptm` files as expected.  Nice!  But it doesn't look like you implemented `HandlerOpenMPT::GetDescription` or `HandlerOpenMPT::GetTags`, which I already have.  Do you want me to push my implementations of those?

I've generally found `libopenmpt` to be more accurate than BASS.  For example, see [this bug report](https://www.un4seen.com/forum/?topic=19958.msg139607#msg139607) I recently filed.  VUPlayer (BASS) has never played that particular MOD file correctly, while OpenMPT always has.

I don't agree with the Linux design philosophy that more choice is always better.  Users shouldn't need to be software developers or understand anything technical about how their app works under the hood in order to have a good default experience with it.  I'd suggest that if you do expose a choice of `libopenmpt`/BASS for each module filetype, VUPlayer should at least default to the best/recommended library for each filetype.

**Comment by jfchapman** [comment]
It was just a quick test of the library, so I didn't implement any tags or playback options for it. I would also need to rejig the options to allow the choice between which library to use, as the mixing options would be different.

I have a large archive of tracker files (100,000+) which I like to scan whenever I upgrade or try new libraries, as it's a good stability test. It's uncovered some problems in the past, particularly for Impulse Tracker files with compressed samples, so I will run this up when I get the chance.

As you've probably guessed, I'm not particularly speedy these days when it comes to updates, but I will be doing more work on this when I get the time.

Thanks,
James

**Comment by jfchapman** [comment]
Hi,

I've pushed some more changes to the libopenmpt_test branch.

This updates the libopenmpt version to 0.6.9, and adds an option to choose the preferred decoder between BASS or libopenmpt (libopenmpt will always be used if BASS can't handle the file format).
I also added some options to control the libopenmpt render params (stereo separation, ramping, interpolation) and an option to fade out songs if they are looped.

I will merge the changes into the main branch for the next release, whenever that may be (things like redundancies, new jobs, etc. have got in the way recently!)

Thanks,
James

**Comment by jfchapman** [comment]
Hi,

I've added libopenmpt to the latest 4.16 release, and it is now the default decoder for all tracked music files. I also added an option to change the decoder settings in the options page (stereo separation, interpolation, etc).

So, hopefully the application will now play back .mptm files (or any other file type) that the libopenmpt library supports.

Thanks,
James

**Comment by c0d3h4x0r** [comment]
Oh wow, nice!!  I'll give it a try!


_______________________

Keith F. Kelly

https://www.keithfkelly.info/


________________________________
