### ISSUE TITLE
Please help find Equalizer

### ISSUE THREAD

**Issue by egnzap** [jfchapman/VUPlayer#4]
I've checked all the Menu... cann't find it !
Thanks !

**Comment by jfchapman** [comment]
That's en easy one to answer, there is no equalizer to find!
It's one of the things I haven't got round to re-implementing yet from the old versions, but it is on the list of things to do.

**Comment by egnzap** [comment]
What's the latest version that still has it?
I use the v. 2.49 
Thanks !

**Comment by jfchapman** [comment]
Yes, 2.49 was the last version that had the equalizer.
It will be back in the next release of version 4.

**Comment by egnzap** [comment]
-- Great News -- !!!

**Comment by jfchapman** [comment]
The equalizer has been implemented in v4.3.

**Comment by egnzap** [comment]
thank you ! Already using the new release
Eugene

**Comment by sergeevabc** [comment]
VU player is buggy as hell in terms of UI.

For example, all buttons are set to be displayed, yet…
![](https://i4.imageban.ru/out/2021/04/07/aa7c45601fefda8765ea915064ea845b.png)

Let’s resize app’s window a bit… Nothing.
![](https://i2.imageban.ru/out/2021/04/07/ffda70eb841cf1fd72f17cde76a60d7e.png)

**Comment by egnzap** [comment]
> VU player is buggy as hell in terms of UI.
> 
> For example, all buttons are set to be displayed, yet…
> ![](https://camo.githubusercontent.com/d9fafd110825f6624dbd76bda570196340eb438da5ddfb866235d040060defbe/68747470733a2f2f69342e696d61676562616e2e72752f6f75742f323032312f30342f30372f61613763343536303166656664613837363565613931353036346561383435622e706e67)
> 
> Let’s resize app’s window a bit… Nothing.
> ![](https://camo.githubusercontent.com/3dd19ed0291bd1b8a46784e02bc54a1ab29d8054c6ada72c2c8e85f551ad270b/68747470733a2f2f69322e696d61676562616e2e72752f6f75742f323032312f30342f30372f66666461373065623834316366316664373266313763646537366136306437652e706e67)

Russian,
can you please be polite ?

**Comment by sergeevabc** [comment]
@egnzap, sugar coating of slipshod job is not my department, but smashing the truth straight between your English eyes is.
Let’s hope the reported UI bug is caused by COVID-19 ambience and not by a lack of dedication, which is  ubiquitous nowadays.

**Comment by egnzap** [comment]
руски иди в свою Росию и там бейся в лоб. А вот для тебя информация Здесь тебе никто не должен Не нравится молчать и проходи мимо )
