### ISSUE TITLE
Does v4.xx still support Gracenote metadata?

### ISSUE THREAD

**Issue by LiarOnce** [jfchapman/VUPlayer#44]
Will the Gracenote metadata source continue to be available on version 4?
Because some albums don't have metadata in MusicBrainz, while Gracenote has instead.

**Comment by jfchapman** [comment]
Hi,

Unfortunately, Gracenote stopped supporting their free developer license, probably as a result of their acquisition by Nielsen. There is now only paid access to the service, which is not an option for a project like mine, so support was dropped a while ago.

Thanks,
James

**Comment by LiarOnce** [comment]
Thank you for your answer.
