### ISSUE TITLE
Stop at end toggle button

### ISSUE THREAD

**Issue by jeskdm** [jfchapman/VUPlayer#6]
I really miss the stop at end toggle button in the new version. I use the software for playback at shows and it is just not workable to go into the menu for each track and select "stop at end". Ok please consider to add this. Thanks J

**Comment by jfchapman** [comment]
Yes, I just need to create some reasonable icons, and I'll add them to the toolbar. I'll probably also add the ability to show/hide individual toolbars while I'm at it.

**Comment by jeskdm** [comment]
Nice! That will be great! Thank you for the work creating this great player :-)
